import { Job } from '@/types/job';

export const dummyJobs: Job[] = [
  {
    id: "1",
    slug: "senior-frontend-engineer-gojek",
    title: "Senior Frontend Engineer",
    companyName: "Gojek",
    companyLogoUrl: "https://ui-avatars.com/api/?name=Gojek&background=random",
    location: "Jakarta Selatan",
    jobType: "FULL_TIME",
    salaryMin: 15000000,
    salaryMax: 25000000,
    description: "<p>Kami mencari Frontend Engineer yang jago Next.js untuk tim GoFood.</p><p>Tanggung jawab: Optimasi performa web.</p>",
    requirements: [
      "Menguasai React.js & Next.js",
      "Paham TypeScript secara mendalam",
      "Minimal pengalaman 4 tahun"
    ],
    postedAt: "2023-12-18T09:00:00Z",
    closingDate: "2024-01-18T09:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "2",
    slug: "laravel-backend-developer-remote",
    title: "Laravel Backend Developer",
    companyName: "StartUp Maju Jalan",
    companyLogoUrl: "https://ui-avatars.com/api/?name=StartUp+Maju&background=random",
    location: "Remote (Indonesia)",
    jobType: "FREELANCE",
    salaryMin: 8000000,
    salaryMax: 12000000,
    description: "<p>Dibutuhkan backend dev untuk bantu migrasi legacy code ke Laravel 10.</p>",
    requirements: [
      "Expert di Laravel & MySQL",
      "Bisa membuat REST API yang aman",
      "Disiplin kerja remote"
    ],
    postedAt: "2023-12-17T14:00:00Z",
    closingDate: "2023-12-30T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "3",
    slug: "devops-engineer-tokopedia",
    title: "DevOps Engineer",
    companyName: "Tokopedia",
    companyLogoUrl: "https://ui-avatars.com/api/?name=Tokopedia&background=random",
    location: "Jakarta Pusat",
    jobType: "FULL_TIME",
    salaryMin: 18000000,
    salaryMax: 28000000,
    description: "<p>Mencari DevOps Engineer untuk infrastruktur cloud kami.</p>",
    requirements: [
      "Pengalaman dengan Kubernetes & Docker",
      "AWS atau GCP certified",
      "Minimal 3 tahun pengalaman"
    ],
    postedAt: "2023-12-19T10:00:00Z",
    closingDate: "2024-01-20T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "4",
    slug: "mobile-developer-bukalapak",
    title: "Mobile Developer (React Native)",
    companyName: "Bukalapak",
    companyLogoUrl: "https://ui-avatars.com/api/?name=Bukalapak&background=random",
    location: "Bandung",
    jobType: "FULL_TIME",
    salaryMin: 12000000,
    salaryMax: 20000000,
    description: "<p>Developer React Native untuk aplikasi mobile Bukalapak.</p>",
    requirements: [
      "Mahir React Native",
      "Pengalaman dengan Firebase",
      "Minimal 2 tahun"
    ],
    postedAt: "2023-12-16T08:00:00Z",
    closingDate: "2024-01-15T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "5",
    slug: "fullstack-developer-startup",
    title: "Fullstack Developer",
    companyName: "TechStart Indonesia",
    companyLogoUrl: "https://ui-avatars.com/api/?name=TechStart&background=random",
    location: "Yogyakarta",
    jobType: "FULL_TIME",
    salaryMin: 10000000,
    salaryMax: 16000000,
    description: "<p>Fullstack developer untuk startup fintech kami.</p>",
    requirements: [
      "React & Node.js",
      "PostgreSQL knowledge",
      "Minimal 2 tahun"
    ],
    postedAt: "2023-12-15T11:00:00Z",
    closingDate: "2024-01-10T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "6",
    slug: "data-scientist-grab",
    title: "Data Scientist",
    companyName: "Grab",
    companyLogoUrl: "https://ui-avatars.com/api/?name=Grab&background=random",
    location: "Jakarta Selatan",
    jobType: "FULL_TIME",
    salaryMin: 20000000,
    salaryMax: 32000000,
    description: "<p>Data Scientist untuk analytics platform Grab.</p>",
    requirements: [
      "Python & SQL expert",
      "Machine Learning experience",
      "Minimal 3 tahun"
    ],
    postedAt: "2023-12-14T09:00:00Z",
    closingDate: "2024-01-25T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "7",
    slug: "qa-engineer-blibli",
    title: "QA Engineer",
    companyName: "Blibli",
    companyLogoUrl: "https://ui-avatars.com/api/?name=Blibli&background=random",
    location: "Jakarta Barat",
    jobType: "FULL_TIME",
    salaryMin: 9000000,
    salaryMax: 15000000,
    description: "<p>QA Engineer untuk testing aplikasi e-commerce.</p>",
    requirements: [
      "Automation testing",
      "Selenium & Cypress",
      "Minimal 2 tahun"
    ],
    postedAt: "2023-12-13T07:00:00Z",
    closingDate: "2024-01-12T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "8",
    slug: "backend-engineer-shopee",
    title: "Backend Engineer (Go)",
    companyName: "Shopee",
    companyLogoUrl: "https://ui-avatars.com/api/?name=Shopee&background=random",
    location: "Jakarta Selatan",
    jobType: "FULL_TIME",
    salaryMin: 16000000,
    salaryMax: 26000000,
    description: "<p>Backend Engineer Go untuk microservices Shopee.</p>",
    requirements: [
      "Go programming language",
      "Microservices architecture",
      "Minimal 3 tahun"
    ],
    postedAt: "2023-12-12T10:00:00Z",
    closingDate: "2024-01-22T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "9",
    slug: "frontend-designer-agora",
    title: "Frontend Engineer & Designer",
    companyName: "Agora Indonesia",
    companyLogoUrl: "https://ui-avatars.com/api/?name=Agora&background=random",
    location: "Surabaya",
    jobType: "FULL_TIME",
    salaryMin: 11000000,
    salaryMax: 18000000,
    description: "<p>Frontend Engineer dengan design skills untuk UI/UX.</p>",
    requirements: [
      "React & Vue.js",
      "Figma proficiency",
      "Minimal 2 tahun"
    ],
    postedAt: "2023-12-11T14:00:00Z",
    closingDate: "2024-01-08T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "10",
    slug: "cloud-architect-bca",
    title: "Cloud Architect",
    companyName: "Bank BCA",
    companyLogoUrl: "https://ui-avatars.com/api/?name=BCA&background=random",
    location: "Jakarta Pusat",
    jobType: "FULL_TIME",
    salaryMin: 25000000,
    salaryMax: 40000000,
    description: "<p>Cloud Architect untuk transformasi digital BCA.</p>",
    requirements: [
      "AWS & Azure certified",
      "Enterprise architecture",
      "Minimal 5 tahun"
    ],
    postedAt: "2023-12-10T09:00:00Z",
    closingDate: "2024-02-01T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "11",
    slug: "security-engineer-bntech",
    title: "Security Engineer",
    companyName: "BN Technology",
    companyLogoUrl: "https://ui-avatars.com/api/?name=BNTech&background=random",
    location: "Remote",
    jobType: "FULL_TIME",
    salaryMin: 17000000,
    salaryMax: 27000000,
    description: "<p>Security Engineer untuk penetration testing dan security audit.</p>",
    requirements: [
      "Cybersecurity knowledge",
      "OWASP familiarity",
      "Minimal 3 tahun"
    ],
    postedAt: "2023-12-09T11:00:00Z",
    closingDate: "2024-01-28T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "12",
    slug: "product-manager-gojek",
    title: "Product Manager",
    companyName: "Gojek",
    companyLogoUrl: "https://ui-avatars.com/api/?name=Gojek&background=random",
    location: "Jakarta Selatan",
    jobType: "FULL_TIME",
    salaryMin: 19000000,
    salaryMax: 30000000,
    description: "<p>Product Manager untuk GoFood vertical.</p>",
    requirements: [
      "Product strategy experience",
      "Data analytics",
      "Minimal 4 tahun"
    ],
    postedAt: "2023-12-08T13:00:00Z",
    closingDate: "2024-02-05T00:00:00Z",
    createdAt: null,
    updatedAt: null,
  }
];
